/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GraphicInterface;

import DataStructures.Graph;

/**
 *
 * @author Orveo Di Luca
 */
public class ShowBfs_Dfs extends javax.swing.JFrame {
    private static Graph graph; 
    private static String fileRoute;
    /**
     * Creates new form ShowBfs_Dfs
     */
    public ShowBfs_Dfs(Graph graph , String fileRoute) {
        initComponents();
        this.graph = graph; 
        this.fileRoute = fileRoute;
        BFSAreatexto.setText(graph.bfs());
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        back = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        BFSAreatexto = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        DFSAreatexto = new javax.swing.JTextArea();
        BFSButton = new javax.swing.JButton();
        DFS = new javax.swing.JButton();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        back.setBackground(new java.awt.Color(58, 176, 248));
        back.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Regresar.png"))); // NOI18N
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        jPanel1.add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 620, -1, -1));

        BFSAreatexto.setBackground(new java.awt.Color(0, 153, 204));
        BFSAreatexto.setColumns(20);
        BFSAreatexto.setRows(5);
        jScrollPane1.setViewportView(BFSAreatexto);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 250, 380));

        DFSAreatexto.setBackground(new java.awt.Color(0, 153, 204));
        DFSAreatexto.setColumns(20);
        DFSAreatexto.setRows(5);
        jScrollPane2.setViewportView(DFSAreatexto);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 150, -1, 380));

        BFSButton.setBackground(new java.awt.Color(255, 204, 0));
        BFSButton.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        BFSButton.setForeground(new java.awt.Color(0, 102, 204));
        BFSButton.setText("BFS");
        jPanel1.add(BFSButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 550, 90, 50));

        DFS.setBackground(new java.awt.Color(255, 204, 0));
        DFS.setFont(new java.awt.Font("Franklin Gothic Medium Cond", 0, 18)); // NOI18N
        DFS.setForeground(new java.awt.Color(0, 102, 204));
        DFS.setText("DFS");
        jPanel1.add(DFS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 550, 90, 50));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/3.png"))); // NOI18N
        jPanel1.add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 660, 700));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 650, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        
        this.dispose();
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(ShowBfs_Dfs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowBfs_Dfs(graph,fileRoute).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea BFSAreatexto;
    private javax.swing.JButton BFSButton;
    private javax.swing.JButton DFS;
    private javax.swing.JTextArea DFSAreatexto;
    private javax.swing.JLabel Fondo;
    private javax.swing.JButton back;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
